### ISSUE TITLE
[Task Points] Make the language of the task points clearer

### ISSUE THREAD

**Issue by cochfarf** [w3c/wai-roles-responsbilities#28]
From the F2F in Austin. The language of some of the task points was not clear and caused some confusion while working through the decision tree.

**Comment by dboudreau** [comment]
As per our follow up discussions on the face to face meeting in Austin, we have agreed that issues or concerns related to the wording of the task points is beyond the scope of what we are currently working on, and beyond the scope of the feedback we are seeking from the rest of the working group. 

What we are currently focused on is defining the logic of the decision tree, to come up with a sustainable framework to help teams build their own accessibility responsibility breakdown. Since we've also agreed in the WG that this list of task points would not be made available publicly, spending time word smithing the task points does not seem like a good use of our time. Once we have role-specific lists, we might revisit our stance and decide to work on the wording of each task point, but for the time being, we are only using this [master list](https://www.w3.org/WAI/EO/wiki/Accessibility_Checkpoint_Master_List) as a way to test proof that our decision tree cup holds water.

Word smithing the task points is a potential time sink, and is certainly as complicated as crafting success criteria would be in the first place. This is not something we are willing to invest too much energy in, at least at this time.
