### ISSUE TITLE
[Task Points] Language of some tasks points is too technical

### ISSUE THREAD

**Issue by cochfarf** [w3c/wai-roles-responsbilities#29]
From Austin F2F: Some of the task points have wording that is technical and implies the role for that task point would be developer even if that is not correct.

**Comment by dboudreau** [comment]
As per our follow up discussions on the face to face meeting in Austin, we have agreed that issues or concerns related to the wording of the task points is beyond the scope of what we are currently working on, and beyond the scope of the feedback we are seeking from the rest of the working group. 

What we are currently focused on is defining the logic of the decision tree, to come up with a sustainable framework to help teams build their own accessibility responsibility breakdown. Since we've also agreed in the WG that this list of task points would not be made available publicly, spending time word smithing the task points does not seem like a good use of our time. Once we have role-specific lists, we might revisit our stance and decide to work on the wording of each task point, but for the time being, we are only using this [master list](https://www.w3.org/WAI/EO/wiki/Accessibility_Checkpoint_Master_List) as a way to test proof that our decision tree cup holds water.

Word smithing the task points is a potential time sink, and is certainly as complicated as crafting success criteria would be in the first place. This is not something we are willing to invest too much energy in, at least at this time.
