### ISSUE TITLE
[Decision Tree]

### ISSUE THREAD

**Issue by cochfarf** [w3c/wai-roles-responsbilities#30]
From Austin F2F: Include testers/qa into the tree, even if they don't have a role other than creating a test plan or some other "verifies"

**Comment by dboudreau** [comment]
As discussed in our internal ARRM follow up meetings, and following the initial face to face in Anaheim, we have significantly [modified the decision tree](https://www.w3.org/WAI/EO/wiki/Role-Based_Decision_Tree) so that testers would become part of the logic. While our current list of task points are not yet specifically mapped to any kind of QA testing role, we do plan on integrating a few that will map to it before we're done with the process. We trust that this will address the concern of leaving the testers out of this exercise.
