### ISSUE TITLE
[ARRM Survey Results] [4. ARRM Framework Introduction]: EOWG language and style

### ISSUE THREAD

**Issue by JenniferChadwick** [w3c/wai-roles-responsbilities#42]
[Current text on the ARRM Introduction page](https://www.w3.org/WAI/EO/wiki/ARRM_framework_introduction)

Original comments:

Comment 1:

I think an editorial pass is needed on this page to better align it with EOWG's language and style guide conventions.

There are:

* Complicated sentences, like "It provides a method (the "decision tree") to review and evaluate accessibility checkpoints to help in not only identifying the roles but their level of involvement or ownership." -- which could be simplified a bit.
* Missing fullstops, as in "[...] need to be addressed as early as possible in the process This oftentimes starts as early as the design phase, [...]"
* In the sentence "[...] what they actually mean in terms of responsibilities also varies greatly from one organization or team to the next -- "the next" sounds strange to me. Maybe the other? Maybe "the next" is also accepted by you native speakers of English and I am just not aware?

Comment 2:

[These comments are based on the version I reviewed when the survey first came out. It looks like this page has changed since then.]

I think this intro page should present just the important information in the same succinct, focused style as the other intro/overview pages throughout the WAI web site. For example:
* https://www.w3.org/WAI/eval/report-tool/#!/
* https://www.w3.org/WAI/planning/statements/

The broader more conversational approach from an earlier version of this page, could be good for a blog post later when we announce the resource.

Comment 3:

The tone is a bit conversational, which is good but can also feel somewhat informal as if its just one person's opinion. Trying to think of how I may propose edits - but it may take some time.

Resolution: 

[Jenn] See [suggested edits under Issue 41](https://github.com/w3c/wai-roles-responsbilities/issues/41).

**Comment by dboudreau** [comment]
@slhenry 
@bakkenb 
@sharronrush 

After some internal discussions about this, we feel that there is room to tighten the language, the voice, and the tone a little bit in some areas so it's not too informal, but we're not willing to go down the path of rewriting the entirety of the documents to map to the "traditional" voice and tone that EOWG has had for years. 

The main reason for that is that we want this resource to speak to the intended audience of cross-functional team members, and not academics who are looking at this resource as a way to get an authoritative perspective on how to approach accessibility. We are viewing this resource as a companion to the team and therefore feel like it needs a different voice, which we're willing to massage so that it doesn't feel too far from EO's. 

That being said, we are willing (and eager) to discuss this further on a weekly call.

**Comment by dboudreau** [comment]
Bump @slhenry @sharronrush @bakkenb  ^^^

**Comment by bakkenb** [comment]
Understand your perspective. Happy to discuss in a planning meeting when possible.

**Comment by mgifford** [comment]
There have been a lot of changes to the intro text. I think we should be able to close this comment as I am not sure how much of this still applies.   
  
@JenniferChadwick any concerns with this.
