### ISSUE TITLE
[ARRM Survey Results] [5. Role-Based Decision Tree]: Move UX Design up in the decision tree

### ISSUE THREAD

**Issue by cochfarf** [w3c/wai-roles-responsbilities#44]
original comment:
I would put Visual Design and UX Design next to each other at 2 & 3. Content can go to 4. I think people will blame the "content" when really it's a general issue with the page navigation not being laid out properly by a UX designer.

**Comment by dboudreau** [comment]
+KrissAnne Interesting perspective. Thank you for that. It's opened a bit of a can of worms, where we'Re now wondering what the order should be: Visual design, UX design, and Content authoring, or Content authoring, Visual design, and UX design. Do you have a strong preference either way? We're kind of on the fence right now, but we see the value of your point.

We'll have to give it more thought, but wE'll likely make a change to reflect this. We'll keep you posted.

**Comment by dboudreau** [comment]
@kakinney We've given it more thought and decided to move Content Authoring up the structure, so that Visual and UX Design would sit together, as you suggested. We prefer to have Content Authors come first as we feel that UX Design becomes a better catch-all for anything related to design than Content authoring would be. Could that work for you as well?

**Comment by dboudreau** [comment]
@kakinney On second thought, for the purpose of efficiency in treating open issues, i'm going to go ahead and close this one (so we have fewer issues to cover on Friday). We'll be going over the changes as we walk everyone through the latest version of the D-Tree anyway, so if there's a concern, we'll be able to address it then.

https://www.w3.org/WAI/EO/wiki/Role-Based_Decision_Tree
