### ISSUE TITLE
[ARRM Survey Results] [5. Role-Based Decision Tree]: [ED-high]: Selecting Primary owners

### ISSUE THREAD

**Issue by cochfarf** [w3c/wai-roles-responsbilities#48]
original comment:
Surely the decision tree is the process for selecting primary ownership (it says so in each of the steps). Given that, what is the point of the ‘Selecting primary owners’ section? This content seems that it could be incorporated into the steps to help in the decision making.

**Comment by dboudreau** [comment]
+kevin@dewoollery.co.uk - We talked about this in our meetings and decided that in order to maintain consistency throughout our document, that we needed to keep it. However, after some thought, we decided to move it up in the document and use it as a way to help the readers understand the mindset in which they are expected to be to understand how to approach using the decision tree. The new version online reflects that change and we will provide an additional paragraph of text to transition into the tree itself.

**Comment by dboudreau** [comment]
Update to reflect additional changes to reflect the structure of the document:https://www.w3.org/WAI/EO/wiki/Role-Based_Decision_Tree#STEP_1._Primary_Ownership

As it turns out, we ended up doing exactly what you suggested with the details embedded directly in the different steps of the Decision Tree.
