### ISSUE TITLE
[ARRM Survey Results] [5. Role-Based Decision Tree]: [ED-low]: ownership and accountability by product owner

### ISSUE THREAD

**Issue by cochfarf** [w3c/wai-roles-responsbilities#50]
original comment:
Ownership levels: The description of primary ownership implies accountability within different roles. This is a tricky one as the ultimate accountability for product quality and delivery is held by the product owner. Not sure how this can be reflected but it seems this is more of a delegated accountability model.

**Comment by dboudreau** [comment]
@iadawn Well, practically speaking, the Product Owner cannot be held accountable for everything. The whole purpose of this resource is to distribute the workload so that the entire team can take ownership and consequently, be held accountable for parts of the effort required for accessibility. The level of accountability that we are talking about in this resource is within the confines of the work being conducted under the guidance of the Product Owner. 

It's fine to consider that ultimately, the PO will have a special level of accountability on the project, but from the perspective of the work being done, there is a certain level of delegating being implicitly distributed across the entire team, in order to reach the desired accessible outcome.

**Comment by mgifford** [comment]
Like the accessibility subject-matter expert the Product Owner needs to have a cross-project experience. However, adding those two roles to every SC would kinda deflate the value of ARRM. ARRM is most useful to help specific roles have a process to know what they are responsible for (in a primary, secondary or contributor capacity).   
  
I think we can close this issue unless @cochfarf has any additional thoughts.
